### ISSUE TITLE
Distorted graph with 1-4 entries

### ISSUE THREAD

**Issue by ethulin** [mefee/mefee#7]
When you have too few entries to include the red line, it still includes space for it, making the graph look really distorted until you have enough entries for the red line.

![image](https://user-images.githubusercontent.com/19850662/77863696-22515000-71f2-11ea-899b-f9ab3cc36c49.png)

**Comment by harry-peirse** [comment]
Actually the issue here is that the points are all at the same point on the x access, so the graph doesn't know how wide to draw the line. So I think it's an edge case due to bad data.
Should we force users to not enter data for the same point in time twice? Or should we overwrite the  old value if they try?

**Comment by harry-peirse** [comment]
Fixed by adding a days padding either side of points
